# Generated by Django 5.2.7 on 2025-10-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='short_description',
            field=models.TextField(blank=True, help_text='A brief description of the item (max 500 characters)', max_length=500),
        ),
    ]
